### ISSUE TITLE
`0` Multiplier Doesn't Work

### ISSUE THREAD

**Issue by pavlovcik** [ubiquibot/production#13]
> ### [ **[ CLAIM 25 WXDAI ]** ](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMjUwMDAwMDAwMDAwMDAwMDAwMDAifSwibm9uY2UiOiIzMzU0NjMzMjc3NTExMTIzMTA5ODU5OTI4MjcyNTc5NDc0Mzg1MjI0OTU0NDQyMjAzOTE4NDc1NjAwNDY5MzE5MTc2MjA2OTg2Mzk3OSIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4NDAwN0NFMjA4M2M3RjNFMTgwOTdhZUIzQTM5YmI4ZUMxNDlhMzQxZCIsInJlcXVlc3RlZEFtb3VudCI6IjI1MDAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHhmODdjYTQ1ODNDNzkyMjEyZTUyNzIwZDEyN0U3RTBBMzhCODE4YUQxIiwic2lnbmF0dXJlIjoiMHhlOTNkYjE0MjAwMzE0ODk4OWU0ZmU4OTc3MTEzY2M4YjdlNzc4NTljZjdjOWY2YmE5YzA3ZGY3ZTk2ZmUxNTMzMmY5MGIxNGM2YmU1YjVlMTMwMmVkZGQ1ZDE1NzMwM2U0MzNhZDI2MTA1MTExNWMwNGEwMTNiM2Y4NWJhZGVhYjFjIn0=)
> ```0x4007CE20...149a341d```

> Multiplier of 0 still isn't working I guess? @0xcodercrane

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/issues/690#issuecomment-1606994517_

**Comment by Draeieg** [comment]
> > ### [ **[ CLAIM 25 WXDAI ]** ](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMjUwMDAwMDAwMDAwMDAwMDAwMDAifSwibm9uY2UiOiIzMzU0NjMzMjc3NTExMTIzMTA5ODU5OTI4MjcyNTc5NDc0Mzg1MjI0OTU0NDQyMjAzOTE4NDc1NjAwNDY5MzE5MTc2MjA2OTg2Mzk3OSIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4NDAwN0NFMjA4M2M3RjNFMTgwOTdhZUIzQTM5YmI4ZUMxNDlhMzQxZCIsInJlcXVlc3RlZEFtb3VudCI6IjI1MDAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHhmODdjYTQ1ODNDNzkyMjEyZTUyNzIwZDEyN0U3RTBBMzhCODE4YUQxIiwic2lnbmF0dXJlIjoiMHhlOTNkYjE0MjAwMzE0ODk4OWU0ZmU4OTc3MTEzY2M4YjdlNzc4NTljZjdjOWY2YmE5YzA3ZGY3ZTk2ZmUxNTMzMmY5MGIxNGM2YmU1YjVlMTMwMmVkZGQ1ZDE1NzMwM2U0MzNhZDI2MTA1MTExNWMwNGEwMTNiM2Y4NWJhZGVhYjFjIn0=)
> > `0x4007CE20...149a341d`
> 
> > Multiplier of 0 still isn't working I guess? @0xcodercrane
> 
> _Originally posted by @pavlovcik in [ubiquity/ubiquity-dollar#690 (comment)](https://github.com/ubiquity/ubiquity-dollar/issues/690#issuecomment-1606994517)_

https://github.com/ubiquibot/staging/issues/42#issuecomment-1605704489 it does, hasn't been merged into production tho
