### ISSUE TITLE
`0` Multiplier - No Explanation 

### ISSUE THREAD

**Issue by pavlovcik** [ubiquibot/production#16]
The bot should ALWAYS return a comment to explain its behavior. 

I requested that the architecture for the handlers should be modified so that it ALWAYS returns a message, or at least a default generic message, so that we know if the bot is having issues or is down.

I have my multiplier set to 0. The bot should say something like "Skipping generating a payment permit because assignee's payment `multiplier` is `0`."

https://github.com/ubiquity/ubiquity-dollar/issues/722

**Comment by pavlovcik** [comment]
@0xcodercrane there's no changes associated so this shouldn't be marked as completed.

**Comment by pavlovcik** [comment]
@0xcodercrane can you link a pull request or at least a commit for auditing?

**Comment by 0xcodercrane** [comment]
> @0xcodercrane can you link a pull request or at least a commit for auditing?

hard to pick up it right now. but we can audit here by doing a QA

**Comment by 0xcodercrane** [comment]
> Refusing to generate the payment permit because @0xcodercrane's payment `multiplier` is `0`
> 
> ###### If you enjoy the DevPool experience, please follow [Ubiquity on GitHub](https://github.com/ubiquity) and star [this repo](https://github.com/ubiquity/devpool-directory) to show your support. It helps a lot!

@pavlovcik
