### ISSUE TITLE
Refusing to generate the payment permit because@pavlovcik's payment `multiplier` is `0`

### ISSUE THREAD

**Issue by pavlovcik** [ubiquibot/production#22]
`because@pavlovcik's` -> `because @pavlovcik's`

Needs a space.

> Refusing to generate the payment permit because@pavlovcik's payment `multiplier` is `0`

_Originally posted by @ubiquibot[bot] in https://github.com/ubiquibot/production/issues/20#issuecomment-1633767249_

**Comment by 0xcodercrane** [comment]
/multiplier @pavlovcik 0.5 "I am an admin"

**Comment by pavlovcik** [comment]
Oh this should be tested on staging!

**Comment by pavlovcik** [comment]
I wish you linked the proof before marking as complete.

**Comment by wannacfuture** [comment]
> Refusing to generate the payment permit because@0xcodercrane's payment `multiplier` is `0`

I think the pr is not implemented  to the production bot yet.
