### ISSUE TITLE
Demo issue

### ISSUE THREAD

**Issue by pavlovcik** [ubiquibot/production#25]
Test issue

**Comment by pavlovcik** [comment]
lol rugged again

**Comment by pavlovcik** [comment]
> Permit generation skipped since autoPayMode is disabled

https://github.com/ubiquibot/production/blob/3008ed9bc1b4178e42e71665208ef7b7432caa64/.github/ubiquibot-config.yml#L3

That's not right. I want to be able to test the pay.ubq.fi interface so I want it to generate an invalid permit, basically. @rndquu can you help me with this? I need it functional to demo things while pitching people

**Comment by rndquu** [comment]
> > Permit generation skipped since autoPayMode is disabled
> 
> https://github.com/ubiquibot/production/blob/3008ed9bc1b4178e42e71665208ef7b7432caa64/.github/ubiquibot-config.yml#L3
> 
> That's not right. I want to be able to test the pay.ubq.fi interface so I want it to generate an invalid permit, basically. @rndquu can you help me with this? I need it functional to demo things while pitching people. I don't need to actually move money, I can explain that context while presenting.

I'll check it in 2 hours

**Comment by pavlovcik** [comment]
> Permit generation skipped since autoPayMode is disabled

@rndquu should you file a bug fix issue for this? I believe that the error message is misleading, because auto pay mode was enabled?

**Comment by rndquu** [comment]
> > Permit generation skipped since autoPayMode is disabled
> 
> @rndquu should you file a bug fix issue for this? I believe that the error message is misleading, because auto pay mode was enabled?

Yes, the error text is misleading, https://github.com/ubiquity/ubiquibot/issues/523
