### ISSUE TITLE
This payout seems messed up for several reasons:

### ISSUE THREAD

**Issue by pavlovcik** [ubiquibot/production#27]
This payout seems messed up for several reasons:

1. Why is the payout on mainnet?
2. The bot added another label afterwards to change the price

@0xcodercrane let's fix 

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquibot/issues/513#issuecomment-1639789694_

**Comment by wannacfuture** [comment]
> @wannacfuture there is a yml error in the [config](https://github.com/ubiquity/ubiquibot/blob/development/.github/ubiquibot-config.yml) probably introduced [here](https://github.com/ubiquity/ubiquibot/pull/522), could you fix it?

I just opened a new PR.
Could you review it and merge it ASAP?
https://github.com/ubiquity/ubiquibot/pull/529

**Comment by wannacfuture** [comment]
Seems approval from @0xcodercrane  is required.

**Comment by pavlovcik** [comment]
Just disabled "require review from code owners" for merges into `development`

<img width="819" alt="image" src="https://github.com/ubiquibot/production/assets/4975670/8310def9-21c2-4c12-984d-f07c710efea4">

**Comment by pavlovcik** [comment]
Does it make sense to throw an error somewhere that's visible if the config isn't valid? 

For example during payment permit generation we can just post the error log from the yml parse function?

In this way it's explicit vs implicit which should help with usability for future partners.

**Comment by pavlovcik** [comment]
The second issue in the specification was not addressed.

**Comment by pavlovcik** [comment]
It's all in the conversation linked in the specification
