### ISSUE TITLE
Hot fix: Automatic Assign on Opened Pull Request (Assigned to Unrelated Task!)

### ISSUE THREAD

**Issue by pavlovcik** [ubiquibot/production#34]
I was working on https://github.com/ubiquity/ubiquibot/issues/595 and opened up a few pull requests because I need to change several repositories' UbiquiBot configs. After opening up my third pull request https://github.com/ubiquity/ubiquity-dollar/pull/751 I was assigned to an unrelated issue: https://github.com/ubiquity/ubiquity-dollar/pull/595

I assume this has something to do with the fact that the issue number (595) is the same across both repositories. Perhaps the feature did not accomodate for cross repository issue tracking. Please diagnose and fix.

**Comment by pavlovcik** [comment]
@wannacfuture you're great at hot fixes is this interesting for you?

**Comment by wannacfuture** [comment]
let me handle this. Mr.Bot!

**Comment by wannacfuture** [comment]
Hmmm, while investigating this issue some quick questions for you, @pavlovcik 
 Your example pull request says it will resolve an issue on another repo.
 
 Of course it will be possible to assigne pr opener to other repo's issue forcely.
 
 But lets assume that we opened the pr and it says it will resolve an issue on other repo(this repo hasn't installed our bot)
 we will assignee the pr opener to that issue.
 Also, technically speaking, to assignee the hunter to other repo's issue we will need that repo's owner name or something(maybe it can be possible if we do more research about octokit).

**Comment by wannacfuture** [comment]
So, IMO, we should check if the pr is trying to resolve the issue on the same repo or other repo of same orgnization then automatically assign the pr opener to the issue.

rfc, @pavlovcik

**Comment by pavlovcik** [comment]
> But maybe the repo owner doesn't want to assignee people to his issue automatically

Not possible the bot wouldn't have permissions to

**Comment by pavlovcik** [comment]
I will start posting all of these fixes on the @ubiquity/ubiquibot repository in the future. I can't easily transfer this one now.

**Comment by pavlovcik** [comment]
Moved to https://github.com/ubiquity/ubiquibot/issues/666
